config/routes.rb
Rails.application.routes.draw do
  root  'pages#home'
  get 'about', to: 'pages#about'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#logout'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :articles
  get 'signup', to: "users#new"
  resources :users, except: [:new]
  resources :categories, except: [:destory]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 6, maximum: 100}
  validates :description, presence: true, length: { minimum: 6, maximum: 1000 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
	belongs_to :article
	belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :article_categories
	has_many :articles, through: :article_categories
	validates :name, presence: true, uniqueness: true, length: {minimum: 3, maximum: 20}
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :user_name, presence: true, length: {minimum: 3, maximum: 23}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: {with: VALID_EMAIL_REGEX}

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper_method :current_user, :logged_in?

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def logged_in?
		!!current_user
	end

	def require_user
		if !logged_in?
			flash[:alert] = "Please login to continue!"
			redirect_to login_path
		end
	end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit,:update, :destroy]
  before_action :require_user
  before_action :require_same_user, only: [:edit, :update, :destroy]


  def show
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5).order(created_at: :desc )
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(do_whitelisting)
    byebug
    debugger
    @article.user = current_user
    if @article.save
      flash[:notice] = "Articles got saved successfully"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def update
    if @article.update(do_whitelisting)
      flash[:notice] = "Article got updated successfully"
      redirect_to article_path(@article)
    else
      flash[:notice] = "Failed to update the article"
      render 'edit'
    end
  end

  def destroy
    if @article.destroy
      flash[:notice] = "Article deleted successfully"
      redirect_to articles_path
    else 
      flash[:notice] = "Failed to delete article"
      render 'delete'
    end
  end

  private

  def do_whitelisting
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def set_article
    @article = Article.find(params[:id])
  end

  def require_same_user
    if current_user != @article.user
      flash[:alert] = "You can only change your own records"
      redirect_to @article
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :require_admin, except: [:index, :show]

	def show
		@category = Category.find(params[:id])
	end	

	def create
		@category = Category.new(category_params)
		if @category.save
			flash[:notice] = "Category Successfully created"
			redirect_to @category
		else
			render 'new'
		end
	end

	def edit
		@category = Category.find(params[:id])
	end

	def update
	   @category = Category.find(params[:id])
		if @category.update(category_params)
			flash[:notice] = "Successfully updated the category"
			redirect_to category_path
		else
			render 'update'
		end
	end

	def index
		@categories = Category.paginate(page: params[:page], per_page: 5).order(created_at: :desc)
	end

	def new
		@category = Category.new
	end

	private

	def category_params
		params.require(:category).permit(:name)
	end

	def require_admin
		unless logged_in? && current_user.admin?
			flash[:alert] = "You do not have access to do these changes"
			redirect_to categories_path
		end
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	redirect_to articles_path if logged_in?
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new

	end

	def create
		user = User.find_by(email: params[:session][:email])
		if user && user.authenticate(params[:session][:password])
			session[:user_id] = user.id
			flash[:notice] = "Successfully Logged In"
			redirect_to user
		else
			flash.now[:alert] = "Incorrect username and password"
			render 'new'
		end
	end

	def logout
		session[:user_id] = nil
		flash[:notice] = "Logged Out Successfully"
		redirect_to signup_path
	end	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 5 ).order(created_at: :desc )
  end

  def new
    @user = User.new
  end

  def show 
  end

  def create
    @user = User.new(do_whitelisting)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "User signed up sucessfully"
      redirect_to articles_path
    else
      flash[:notice] = "User sign up failed"
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(do_whitelisting)
      flash[:notice] = "Sucessfully updated the user"
      redirect_to users_path  
    else  
      flash[:notice] = "Failed to update the user"
      render 'edit'
    end
  end

  def destroy
    if @user.destroy
      session[:user_id] = nil
      flash[:notice] = "Account deleted Sucessfully"
      redirect_to root_path
    end
  end

  private

  def do_whitelisting
    params.require(:user).permit(:user_name, :email,:password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user
      flash[:alert] = "You can update only your own record"
      redirect_to @user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def gravator_for(user, options= {size: 80})
		email = user.email.downcase
		hash_val = Digest::MD5.hexdigest(email)
		size = options[:size]
		gravator_url = "https://www.gravatar.com/avatar/#{hash_val}?s=#{size}"
		image_tag(gravator_url, alt: user.user_name, class: "rounded mx-auto d-block") 
	end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
<div class="row justify-content-md-center ">
    <div class="col-8 mt-4">
      <div class="card text-center shadow-lg p-3 mb-5 bg-white rounded">
        <div class="card-header">
          by <%= article.user.user_name if article.user %>
        <div class="mt-2">
          <% if article.categories.any? %>
              <%= render article.categories %>
          <% end %>
        </div>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
          <p class="card-text"><%= truncate(article.description, length: 100) %></p>
            <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
            <% if logged_in? && (article.user == current_user || current_user.admin?) %>
              <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-primary" %>
              <%= link_to "Delete", article_path(article), method: :delete, class: "btn btn-outline-danger", data: {confirm: "Are you sure you want to delete the article?"} %>
            <% end %>
        </div>
        <div class="card-footer text-muted">
          Created At:<%= time_ago_in_words(article.created_at) %> | Updated At: <%= time_ago_in_words(article.updated_at) %>
        </div>
      </div>
    </div>
  </div>
<%end%>

app/views/articles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @article %>
      <%= form_with(model: @article, local: true) do |f| %>
          <div class="form-group row">
            <%= f.label :title, class: "col-2 col-form-label" %> 
             <div class="col-10">
              <%= f.text_field :title, class: "form-control shadow rounded" %>
             </div> 
          </div> 

        <div class="form-group row">
          <%= f.label :description, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :category, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.collection_select(:category_ids, Category.all, :id, :name, {prompt: "Make your selections"}, {multiple: true, size: 5,class: "custom-select shadow rounded"} ) %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-success" %>
        </div>
    <%= link_to 'Return to Main Page', articles_path, class: "justify-content-center" %>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/create.html.erb
<h1>Articles#create</h1>
<p>Find me in app/views/articles/create.html.erb</p>

app/views/articles/delete.html.erb
<h1>Articles#delete</h1>
<p>Find me in app/views/articles/delete.html.erb</p>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4"><strong> Edit Article </strong></h1>
<%= render 'articles/form' %>
<%= link_to 'Return to Main Page', articles_path %>

app/views/articles/index.html.erb
<h1 class= "text-center mt-4">Articles listing page </h1>

<div class="flickr_pagination">
  <div class="page_info">
    <%= page_entries_info @articles %>
  </div>
   <%= will_paginate @articles, :container => false %>
</div>

<%= render 'article', obj: @articles %>

<div class="flickr_pagination mt-4">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4"><strong> Create a New Article </strong></h1>  

<%= render 'form' %>

app/views/articles/show.html.erb
<h1 class= "text-center mt-4"><%= @article.title %></h1>

<div class="row justify-content-md-center ">
    <div class="col-8 mt-4">
      <div class="card text-center shadow-lg p-3 mb-5 bg-white rounded">
        <div class="card-header">
          by <%= @article.user.user_name if @article.user %>
          <div class="mt-2">
            <%= render @article.categories %>
          </div>
        </div>
        <div class="card-body">
          <div class="card-text text-left"><%= simple_format(@article.description) %></div>
          <% if logged_in? && current_user == @article.user %>
              <%= link_to "Delete", article_path(@article), method: :delete, class: "btn btn-outline-danger", data: {confirm: "Are you sure you want to delete the article?"} %>
              <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-primary" %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          Created At:<%= time_ago_in_words(@article.created_at) %> | Updated At: <%= time_ago_in_words(@article.updated_at) %>
        </div>
        <%= link_to 'Return to Main Page', articles_path, class: "justify-content-center" %>
      </div>
    </div>
  </div>

app/views/articles/update.html.erb
<h1>Articles#update</h1>
<p>Find me in app/views/articles/update.html.erb</p>

app/views/categories/_category.html.erb
<span ><%= link_to category.name, category_path(category), class: "badge badge-pill badge-info mr-1" %></span>

app/views/categories/_form.html.erb
<div class="container">
	<div class="row justify-content-center">
	    <div class="col-10">
	      <%= render 'shared/errors', obj: @category %>
	      <%= form_with(model: @category, local: true) do |f| %>
	          <div class="form-group row">
	            <%= f.label :name,"Categry Name", class: "col-2 col-form-label" %> 
	             <div class="col-10">
	              <%= f.text_field :name, class: "form-control" %>
	             </div> 
	          </div> 
	        <div class="form-group row justify-content-center">
	          <%= f.submit @category.new_record? ? "Create" : "Update", class: "btn btn-outline-success" %>
	        </div>
	    <%= link_to 'Return to Main Page', articles_path, class: "justify-content-center" %>
	      <% end %>
	    </div>
	</div>
</div>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4"> Update Category </h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 class="text-center mt-4"> Categories Listing</h1>

<div class="flickr_pagination">
  <div class="page_info">
    <%= page_entries_info @categories %>
  </div>
   <%= will_paginate @categories, :container => false %>
</div>

<% @categories.each do |category| %>
<div class="row justify-content-md-center ">
    <div class="col-8 mt-4">
      <div class="card text-center shadow-lg p-3 mb-5 bg-white rounded">
        <div class="card-header">
          by <%= category.name%>
          <div class="mt-2">
          	 <%= pluralize(category.articles.count, "article") %>
          </div>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-success" %></h5>
        </div>
        <div class="card-footer text-muted">
          Created At:<%= time_ago_in_words(category.created_at) %> | Updated At: <%= time_ago_in_words(category.updated_at) %>
        </div>
      </div>
    </div>
  </div>
<%end%>

<div class="flickr_pagination mt-4">
  <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4"> Create a new Category </h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1 class="text-center mt-4 "> Category: <%= @category.name %> </h1>
<div class="text-center">
	<%= link_to "Edit category", edit_category_path(@category), class: "btn btn-primary"%>
</div>
<% if @category.articles.any? %>
<% @category.articles.each do |article| %>
<div class="row justify-content-md-center ">
    <div class="col-8 mt-4">
      <div class="card text-center shadow-lg p-3 mb-5 bg-white rounded">
        <div class="card-header">
          by <%= article.user.user_name%>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
        </div>
        <div class="card-footer text-muted">
          Created At:<%= time_ago_in_words(article.created_at) %> | Updated At: <%= time_ago_in_words(article.updated_at) %>
        </div>
      </div>
    </div>
  </div>
<%end%>
<% else %>
<h3 class="text-center mt-4">There is no articles assoicated with this category.</h3>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white-50">
  <div class="container text-center">
    <small>Copyright @2021</small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |key, msg| %>
     <div class="alert alert-<%= key == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Bloggers", users_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Articles
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%=  link_to "Create New", new_article_path, class: "dropdown-item" %>
              <%=  link_to "View Listing Page", articles_path, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
          <% if logged_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Categories
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "New Category", new_category_path, class: "dropdown-item" %>
                <%= link_to "View Categories", categories_path, class: "dropdown-item" %>
                <div class="dropdown-divider"></div>
              </div>
            </li>
          <% end %>
          <% if logged_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Profile [<%= current_user.user_name if logged_in? %>]
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%=  link_to "View Profile", user_path(current_user), class: "dropdown-item" %>
                <%=  link_to "Edit User Profile", edit_user_path(current_user), class: "dropdown-item" %>
                <div class="dropdown-divider"></div>
                <%= link_to "Delete your Profile", user_path(current_user), method: :delete, data: { confirm: "Are you sure you want to delete your profile?" }, class: "dropdown-item text-danger"  %>
            </li>
          <% end %>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          <% if logged_in? %>
            <%= link_to "Logout", logout_path, method: :delete, class: "nav-link"%> 
          <% else %>
            <%= link_to "Login", login_path, class: "nav-link"%> 
          <% end %>
        </form>
      </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestDev</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>ABOUT THIS APP</h1>

app/views/pages/home.html.erb
<div class="container" id="home-container">
  <div class="jumbotron text-center text-white">
    <h1 class="display-4">Alpha Blog</h1>
    <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <% if !logged_in? %>
    	<%= link_to "Sign Up", signup_path, class: "btn btn-success btn-lg", role: "button" %>
    <% end %>
  </div>  
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented <%= obj.class.name %> to save</h4>
      <ul>
        <%  obj.errors.full_messages.each do |err| %>
        <li>
          <%= err %>
        </li>
        <% end %>
      </ul>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @user %>
      <%= form_with(model: @user, local: true) do |f| %>
          <div class="form-group row">
            <%= f.label :user_name, class: "col-2 col-form-label" %> 
             <div class="col-10">
              <%= f.text_field :user_name, class: "form-control" %>
             </div> 
          </div> 

        <div class="form-group row">
          <%= f.label :email, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.email_field :email, class: "form-control", placeholder: "Enter your email address" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :password, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.password_field :password, class: "form-control", placeholder: "Enter your password" %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit(@user.new_record? ? "Sign Up" : "Update User", class: "btn btn-outline-success") %>
        </div>
    <%= link_to 'Return to Main Page', articles_path, class: "justify-content-center" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4"><strong> Edit User </strong></h1>
<%= render 'users/form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4"><strong> Blogger's List </strong></h1>  

<% @users.each do |user| %>
<div class="row justify-content-md-center ">
    <div class="col-8 mt-4">
      <div class="card text-center shadow-lg p-3 mb-5 bg-white rounded">
        <div class="card-header">
           <%= link_to user.user_name, user %>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= link_to gravator_for user, user %></h5>
          <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
            <%= link_to "Edit", edit_user_path(user), class: "btn btn-outline-primary" %>
            <%= link_to "View", user, class: "btn btn-outline-success" %>

        </div>
        <div class="card-footer text-muted">
          Join:<%= time_ago_in_words(user.created_at) %> 
        </div>
      </div>
    </div>
  </div>
<%end%>

<div class="flickr_pagination">
  <div class="page_info">
    <%= page_entries_info @users %>
  </div>
   <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4"><strong> Sign Up for Alpha Blog </strong></h1>  

<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><strong> <%= @user.user_name %>'s Profile </strong></h1>
<%= gravator_for @user, size: 200 %>

<div class="text-center mt-4">
	<%= link_to "Update User Info", edit_user_path(@user) %>
</div>
<h3 class="text-center mt-4"><strong> Articles </strong></h3>

<%= render "articles/article", obj: @user.articles %>